name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Frontend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dream-vacation-app-frontend:latest ./frontend

      - name: Build Backend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dream-vacation-app-backend:latest ./backend

      - name: Push Frontend Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dream-vacation-app-frontend:latest

      - name: Push Backend Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dream-vacation-app-backend:latest

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            docker-compose pull
            docker-compose down
            docker-compose up -d --remove-orphans
